apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: api-key-volume
          secret:
            secretName: api-key-secret
      containers:
      - name: nginx
        image: demo/nginx:latest
        imagePullPolicy: Never
        envFrom:
          - secretRef:
              name: api-key-secret
        ports:
        - containerPort: 80
        volumeMounts:
          - name: api-key-volume
            mountPath: "/etc/api-key-volume"
